### ISSUE TITLE
thoughtbot

### ISSUE THREAD

**Issue by tysongach** [design-systems-coalition-NYC/meetup#22]
[We (thoughtbot)](https://thoughtbot.com/) would love to help by offering [our space](https://thoughtbot.com/new-york-city) to host the meetup.

**Comment by broccolini** [comment]
@tysongach Awesome! Could you give me an email contact? I can send over details as to what's involved and discuss when you would be available to host. If you like, send an email to `designsystems.nyc@gmail.com` rather than sharing your email here.
