### ISSUE TITLE
ustwo

### ISSUE THREAD

**Issue by anniemalarkey** [design-systems-coalition-NYC/meetup#26]
We (ustwo) have an open event space that can seat up to 110 people and we are interested in hosting a future meetup. We are located at 26 Broadway in the Financial District. 
![event-space-mural](https://user-images.githubusercontent.com/30531428/28724847-72a707e4-7389-11e7-94d2-950944841032.jpg)

**Comment by broccolini** [comment]
Thanks @anniemalarkey! Your space looks great. We do have the next couple of hosts lined up but may be looking for a host for September or October. Check out the [hosting guidelines](https://github.com/design-systems-coalition-NYC/meetup/blob/master/hosting-guidelines.md) for more information.

Usually someone from the hosting company speaks and we try and find a specific topic to cover that  is of interest to the community and works for the hosts. Some [ideas are listed here](https://github.com/design-systems-coalition-NYC/meetup/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic+idea%22), but happy to discuss other topics too.

**Comment by anniemalarkey** [comment]
Great! We'd love to host and we could definitely have someone speak on one of these topics. September or October should give us enough time to prep. My email is annie at ustwo.com if you'd like to chat directly!

**Comment by broccolini** [comment]
Thanks @anniemalarkey I'll get in touch via email :)

**Comment by anniemalarkey** [comment]
Hi @broccolini Looks like you have a venue for this month, but I'd still love to chat with you about hosting in the future! Thanks.

**Comment by anniemalarkey** [comment]
Hi @broccolini -- are you still looking for venues next year? We can seat up to 120 people and would love to present our Design System we built for https://www.ssense.com/. We'd be happy to sponsor food and drinks. Thanks!
