### ISSUE TITLE
Grubhub design / dev teams for April meetup

### ISSUE THREAD

**Issue by johncoghlan** [design-systems-coalition-NYC/meetup#43]
The Grubhub design and development teams have been investing heavily in developing pattern libraries and adopting a style-guide-driven-development approach for parts of our application. Our team would love to speak at an upcoming meetup.

**Comment by johncoghlan** [comment]
Here's a blog post on SGDD: https://bytes.grubhub.com/style-guide-driven-development-the-android-pattern-library-b19ed24d4ec4

**Comment by broccolini** [comment]
I'm sorry I didn't see this sooner. I'll keep you in mind for future meetups though. Thanks for reaching out!
